#!/usr/bin/python
import sys
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
sys.path.insert(0,currentdir + '/bin')

import arguments










if __name__ == '__main__':
	objective, args=arguments.fullParser(sys.argv[1:])
	
	if objective == 'preprocess':
		import runpreprocess
		runpreprocess.runAll(args)
		
	elif objective == 'map':
		import runmap
		runmap.runAll(args)
		
	elif objective == 'count':
		import runcount
		runcount.runAll(args)
		
	elif objective == 'segment':
		import runsegment
		runsegment.runAll(args)
		
	elif objective == 'interpret':
		import runinterpret
		runinterpret.runAll(args)
				
		
		
	else:
		errorText = '\n\n\nERROR: specified function ' + objective + ' is not supported at this time\n'
		errorText += 'Calling somaticCNVcalling -h for enumeration of existing functions...\n'
		print(errorText)
		arguments.fullParser('-h')
		
		
		
		
		
		
		
		
		
		
