#!/usr/bin/python
import sys

import arguments










if __name__ == '__main__':
	objective, args=arguments.fullParser(sys.argv[1:])
	
	if objective == 'preprocess':
		import runpreprocess
		runpreprocess.runAll(args)
		
	elif objective == 'map':
		import runmap
		runmap.runAll(args)
		
	elif objective == 'count':
		import runcount
		runcount.runAll(args)
		
		
		
		
	else:
		errorText = '\n\n\nERROR: specified function ' + objective + ' is not supported at this time\n'
		errorText += 'Please try somaticCNVcalling -h for enumeration of existing functions\n\n\n'
		print(errorText)
		raise SystemExit
		
		
		
		
		
		
		
		
		
		
